sudo: false
language: node_js
node_js: '4'
cache:
  directories: node_modules
before_script: npm prune
branches:
  except: /^v\d+\.\d+\.\d+$/
notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/df4440290bd89d941fb4
    on_success: change
    on_failure: always
    on_start: false
  email: false
script: npm run test-ci
addons:
  sauce_connect: true
env:
  global:
  - secure: E6+5DMGxgqgeq7ycXFFo2BrUQRIiWt1he/hGxDMT5+CXO31alA61pJ8bY+87gg2XYHTdbV5SkyhPp8STOCkeexhYEhY7N1HiPkiWSV4bXHxcWDVOVFGgVOR4QwOFWuN84yhm9VqTYB/JMQcj4U3SfreAp/bmjiSToU+KFkrNuSI=
  - secure: Ikstu2XYI8kcvEU8083eVtHfU0yUUmJRorh6kIy+Wi7J0lpsK2NhFVkKIKYMyzU9axv8u1dk3Qq4Do6Sn83+9pKia2m0vbWboarC792qb6CT58+Uc9z4T440OzM+ng8d7pAUljXfcabaXFC962sw1l2SWIm0dtzSjGt/ThqfEuI=
